# Generated by Django 4.1.4 on 2023-01-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardailytracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='worked_By',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
