# Generated by Django 4.1.4 on 2023-02-08 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ardailytracker', '0002_alter_detail_worked_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceAssignment',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='comment_1',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='comment_2',
        ),
        migrations.RemoveField(
            model_name='detail',
            name='status_1',
        ),
        migrations.AddField(
            model_name='detail',
            name='account_Status1',
            field=models.CharField(blank=True, choices=[('Clarification', 'Clarification'), ('In-process', 'In-process'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='aging_Lag',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detail',
            name='status_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='allocation_Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='disposition',
            field=models.CharField(blank=True, choices=[('Patient', 'Patient'), ('Medical Records/Appeal in Process', 'Medical Records/Appeal in Process'), ('Submitted', 'Submitted'), ('Payment Pending', 'Payment Pending'), ('Ready to Submit', 'Ready to Submit'), ('AMED Review - Coding Handoff', 'AMED Review - Coding Handoff'), ('From WFH', 'From WFH'), ('Cur-Review-MedRec/Authorization', 'Cur-Review-MedRec/Authorization'), ('ERA Payer Denied', 'ERA Payer Denied'), ('Medical Record Sent', 'Medical Record Sent'), ('CUR Review Appeal', 'CUR Review Appeal'), ('-', '-'), ('AMED Review-Insurance contaced', 'AMED Review-Insurance contaced'), ('To WFH', 'To WFH'), ('Manual payment denial', 'Manual payment denial')], max_length=200, null=True),
        ),
    ]
