# Generated by Django 4.1.4 on 2023-02-08 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardailytracker', '0003_delete_resourceassignment_remove_detail_comment_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='account_Status1',
            new_name='account_Status',
        ),
    ]
